### PR TITLE
update kiss metrics script

### PR DESCRIPTION
**Pull request by yzhang**
seems kiss metrics script is outdated, and here's the updated one.

### CODE REVIEW

**Comment by clickonchris** [comment]
I had gotten KM working with analytical a few weeks ago by configuring my js_url_key to be

'//doug1izaerwt3.cloudfront.net/my-km-key.1.js'

If this change gets integrated I would need to update my js_url_key to be

'my-km-key'

Just an observation - it could be useful as part of some upgrade notes

**Comment by freerobby** [comment]
@yzhang Thanks for the PR. I don't want to merge this into master, which is used for minor/point releases, because as @clickonchris explained it will break tracking for users who are expecting the current behavior. I see two options moving forward:

1) Keep this PR open, and merge it into the next major release of analytical.
2) Add logic to the gem that checks for the format of `my-km-key` and gsub away the URL characters if needed.

**Comment by sfsekaran** [comment]
Could you modify the config to detect and work both ways? I see no reason why it should not allow people to choose whichever way they want, at least for now.

**Comment by sfsekaran** [comment]
I'm going to close this pull request for now, it's been lingering for quite a while. Please resubmit after it's backwards compatible :+1:

**Pull request closed without merging**
