### PR TITLE
Add Mixpanel#person and Mixpanel#revenue methods

### PR DESCRIPTION
**Pull request by clupprich**
Adds the new Mixpanel revenue functionality and allows setting of people attributes. Includes specs :)

### CODE REVIEW

**Comment by sfsekaran** [comment]
Would it be too much trouble to have you make the analytical option the exact same name as the mixpanel option? I.e. instead of `:track`, it would be `:track_pageviews`? I realize this is a small change, but I feel it's important to reduce synonymic confusion between the two systems. I'm willing to be argued with if you disagree. Other than that, I see no problem merging this request.

**Comment by clupprich** [comment]
Sure, I will amend my pull request!

**Comment by sfsekaran** [comment]
You know what? I'll do it myself. No need to bother you further :). Thanks for the pull request!

**Comment by clupprich** [comment]
I'm confused ;). The reason I did this pull request is that we want to use less data points but the default behaviour was set to track pageviews. I left it that way and just introduced the posibility to disable it.

**Comment by clupprich** [comment]
See here: https://mixpanel.com/docs/integration-libraries/javascript-full-api#track_pageview (although the Mixpanel documentation is quite confusing these days because they currently serve two types of documentation)

**Comment by sfsekaran** [comment]
Christoph, thanks for clearing this up. It's definitely a bit confusing.

I'll pull the other commits in now, it now makes total sense to me why you implemented it. A default of `true` is good because, like you said, that's their default.

Thanks again! Help is always, _always_ appreciated.

**Pull request closed without merging**
