### PR TITLE
Implement the name_tag method.

### PR DESCRIPTION
**Pull request by jellybob**
It's a really rough patch, because I'm just hacking something together, but this implements the name_tag method for Mixpanel.

### CODE REVIEW

**Comment by jkrall** [comment]
Hey... thanks for this.  Before I merge it in... can you give me a quick explanation of what the name_tag MixPanel method does?

If it's truly a unique-to-MixPanel method, then this is exactly right.  But I want to double-check that it's not related to the track() or identify() method instead, because whenever possible the goal is to keep the APIs unified across the different analytics providers.

Thanks!

**Comment by jellybob** [comment]
It sets the name attached to a user in their UI. Thinking about it passing a
:name option to identify would probably make more sense, but it would still
need to call name_tag in their JavaScript API.
On Oct 17, 2011 7:31 PM, "Joshua Krall" <
reply@reply.github.com>
wrote:

**Comment by jkrall** [comment]
Ah yeah, that makes sense.

My gut says: have `#identify` accept an optional `:name=>'name'` attribute,
and then append the call to MixPanel's `name_tag` function after the
existing `#identify` functionality... does that make sense?

Maybe we should keep this additional `#name_tag` method but also add the
functionality to `#identify` so that users who don't want to add
MixPanel-specific stuff into their analytical calls still get the benefit of
`name_tag`?

If this makes sense... and you have time... go ahead and add this
functionality to this commit, and I'll gladly merge this in.
Thanks!

**Comment by jkrall** [comment]
Closing this one, because it was handled here:  https://github.com/jkrall/analytical/pull/31

**Pull request closed without merging**
